server:
  port: 8090
  servlet:
    context-path: /gg-onething

#数据源
spring:
  datasource:
    was:
      #url: jdbc:mysql://172.22.177.11:3306/was?useUnicode=true&characterEncoding=utf8
      url: jdbc:mysql://127.0.0.1:3306/was?useUnicode=true&characterEncoding=utf8
      username: root
      password: root2017
      driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 30MB #最大请求文件的大小
      max-file-size: 50MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入

#打印sql，方便调试
mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

