package com.linewell.gg.dao.mapperwas.module;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table apas_attr
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ApasAttr implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.UNID
     *
     * @mbg.generated
     */
    private String unid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.PUNID
     *
     * @mbg.generated
     */
    private String punid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.MATERIALID
     *
     * @mbg.generated
     */
    private String materialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.SAVESTATE
     *
     * @mbg.generated
     */
    private String savestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.ISCHECKED
     *
     * @mbg.generated
     */
    private String ischecked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.CREATETIME
     *
     * @mbg.generated
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.FROMSHARE
     *
     * @mbg.generated
     */
    private String fromshare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.LOCKED
     *
     * @mbg.generated
     */
    private Integer locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.SORTID
     *
     * @mbg.generated
     */
    private Integer sortid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.AMOUNT
     *
     * @mbg.generated
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.PHASE
     *
     * @mbg.generated
     */
    private String phase;

    /**
     * Database Column Remarks:
     *   补件要求
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_attr.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apas_attr
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.UNID
     *
     * @return the value of apas_attr.UNID
     *
     * @mbg.generated
     */
    public String getUnid() {
        return unid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.UNID
     *
     * @param unid the value for apas_attr.UNID
     *
     * @mbg.generated
     */
    public void setUnid(String unid) {
        this.unid = unid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.PUNID
     *
     * @return the value of apas_attr.PUNID
     *
     * @mbg.generated
     */
    public String getPunid() {
        return punid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.PUNID
     *
     * @param punid the value for apas_attr.PUNID
     *
     * @mbg.generated
     */
    public void setPunid(String punid) {
        this.punid = punid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.MATERIALID
     *
     * @return the value of apas_attr.MATERIALID
     *
     * @mbg.generated
     */
    public String getMaterialid() {
        return materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.MATERIALID
     *
     * @param materialid the value for apas_attr.MATERIALID
     *
     * @mbg.generated
     */
    public void setMaterialid(String materialid) {
        this.materialid = materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.NAME
     *
     * @return the value of apas_attr.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.NAME
     *
     * @param name the value for apas_attr.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.SAVESTATE
     *
     * @return the value of apas_attr.SAVESTATE
     *
     * @mbg.generated
     */
    public String getSavestate() {
        return savestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.SAVESTATE
     *
     * @param savestate the value for apas_attr.SAVESTATE
     *
     * @mbg.generated
     */
    public void setSavestate(String savestate) {
        this.savestate = savestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.ISCHECKED
     *
     * @return the value of apas_attr.ISCHECKED
     *
     * @mbg.generated
     */
    public String getIschecked() {
        return ischecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.ISCHECKED
     *
     * @param ischecked the value for apas_attr.ISCHECKED
     *
     * @mbg.generated
     */
    public void setIschecked(String ischecked) {
        this.ischecked = ischecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.CREATETIME
     *
     * @return the value of apas_attr.CREATETIME
     *
     * @mbg.generated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.CREATETIME
     *
     * @param createtime the value for apas_attr.CREATETIME
     *
     * @mbg.generated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.FROMSHARE
     *
     * @return the value of apas_attr.FROMSHARE
     *
     * @mbg.generated
     */
    public String getFromshare() {
        return fromshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.FROMSHARE
     *
     * @param fromshare the value for apas_attr.FROMSHARE
     *
     * @mbg.generated
     */
    public void setFromshare(String fromshare) {
        this.fromshare = fromshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.LOCKED
     *
     * @return the value of apas_attr.LOCKED
     *
     * @mbg.generated
     */
    public Integer getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.LOCKED
     *
     * @param locked the value for apas_attr.LOCKED
     *
     * @mbg.generated
     */
    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.SORTID
     *
     * @return the value of apas_attr.SORTID
     *
     * @mbg.generated
     */
    public Integer getSortid() {
        return sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.SORTID
     *
     * @param sortid the value for apas_attr.SORTID
     *
     * @mbg.generated
     */
    public void setSortid(Integer sortid) {
        this.sortid = sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.MEMO
     *
     * @return the value of apas_attr.MEMO
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.MEMO
     *
     * @param memo the value for apas_attr.MEMO
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.AMOUNT
     *
     * @return the value of apas_attr.AMOUNT
     *
     * @mbg.generated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.AMOUNT
     *
     * @param amount the value for apas_attr.AMOUNT
     *
     * @mbg.generated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.PHASE
     *
     * @return the value of apas_attr.PHASE
     *
     * @mbg.generated
     */
    public String getPhase() {
        return phase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.PHASE
     *
     * @param phase the value for apas_attr.PHASE
     *
     * @mbg.generated
     */
    public void setPhase(String phase) {
        this.phase = phase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_attr.REMARK
     *
     * @return the value of apas_attr.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_attr.REMARK
     *
     * @param remark the value for apas_attr.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}