package com.linewell.gg.dao.mapperwas.module;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table apas_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ApasInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.UNID
     *
     * @mbg.generated
     */
    private String unid;

    /**
     * 一件事实例unid
     */
    private String moduleUnid;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.PARENTID
     *
     * @mbg.generated
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.SERVICEID
     *
     * @mbg.generated
     */
    private String serviceid;

    private String servicecode;

    public String getServicecode() {
        return servicecode;
    }

    public void setServicecode(String servicecode) {
        this.servicecode = servicecode;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.SERVICENAME
     *
     * @mbg.generated
     */
    private String servicename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.SERVICETYPE
     *
     * @mbg.generated
     */
    private String servicetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.PROMISEDAY
     *
     * @mbg.generated
     */
    private Integer promiseday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.PROJ_CODE
     *
     * @mbg.generated
     */
    private String projCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.INFOTYPE
     *
     * @mbg.generated
     */
    private String infotype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.PROJID
     *
     * @mbg.generated
     */
    private String projid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.PROJPWD
     *
     * @mbg.generated
     */
    private String projpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.HANDLESTATE
     *
     * @mbg.generated
     */
    private String handlestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.PROJECTNAME
     *
     * @mbg.generated
     */
    private String projectname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.APPLYNAME
     *
     * @mbg.generated
     */
    private String applyname;

    /**
     * Database Column Remarks:
     *   申请人手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.MOBILE
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   经办人手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.PHONE
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.POSTCODE
     *
     * @mbg.generated
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.CONTACTMAN
     *
     * @mbg.generated
     */
    private String contactman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.LEGALMAN
     *
     * @mbg.generated
     */
    private String legalman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.FORMID
     *
     * @mbg.generated
     */
    private String formid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.APPLYFROM
     *
     * @mbg.generated
     */
    private String applyfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.IDCARD
     *
     * @mbg.generated
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.DELETEFLAG
     *
     * @mbg.generated
     */
    private String deleteflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.CREATE_USERNAME
     *
     * @mbg.generated
     */
    private String createUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.CREATE_USERID
     *
     * @mbg.generated
     */
    private String createUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.RECEIVE_USERNAME
     *
     * @mbg.generated
     */
    private String receiveUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.RECEIVE_USERID
     *
     * @mbg.generated
     */
    private String receiveUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.RECEIVE_DEPTNAME
     *
     * @mbg.generated
     */
    private String receiveDeptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.RECEIVE_DEPTID
     *
     * @mbg.generated
     */
    private String receiveDeptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.RECEIVE_TIME
     *
     * @mbg.generated
     */
    private String receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.PREJUDGE_TIME
     *
     * @mbg.generated
     */
    private String prejudgeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.ACCEPT_TIME
     *
     * @mbg.generated
     */
    private String acceptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.NODE_STIME
     *
     * @mbg.generated
     */
    private String nodeStime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.NODE_ETIME
     *
     * @mbg.generated
     */
    private String nodeEtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.TRANSACT_TIME
     *
     * @mbg.generated
     */
    private String transactTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.GET_TIME
     *
     * @mbg.generated
     */
    private String getTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.PROMISE_ETIME
     *
     * @mbg.generated
     */
    private String promiseEtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.EFFISTATE
     *
     * @mbg.generated
     */
    private String effistate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.EFFIVALUE
     *
     * @mbg.generated
     */
    private Integer effivalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.GREEN_WAY
     *
     * @mbg.generated
     */
    private String greenWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.APPLYCOUNT
     *
     * @mbg.generated
     */
    private Integer applycount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.RESULT
     *
     * @mbg.generated
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.RESULT_CODE
     *
     * @mbg.generated
     */
    private String resultCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.UNITE_NOTICE_CODE
     *
     * @mbg.generated
     */
    private String uniteNoticeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.UNITE_PROJECT_INFO
     *
     * @mbg.generated
     */
    private String uniteProjectInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.UNITE_OPINION_CONTENT
     *
     * @mbg.generated
     */
    private String uniteOpinionContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.UNITE_OPINION_USERNAME
     *
     * @mbg.generated
     */
    private String uniteOpinionUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.UNITE_OPINION_DATETIME
     *
     * @mbg.generated
     */
    private String uniteOpinionDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.UNITE_OPINION_USERUNID
     *
     * @mbg.generated
     */
    private String uniteOpinionUserunid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.PROMISETYPE
     *
     * @mbg.generated
     */
    private String promisetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.DISTANCEDAY
     *
     * @mbg.generated
     */
    private Integer distanceday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.TERMINATE_USERID
     *
     * @mbg.generated
     */
    private String terminateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.TERMINATE_USERNAME
     *
     * @mbg.generated
     */
    private String terminateUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.DEAL_OFFICE
     *
     * @mbg.generated
     */
    private String dealOffice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.DEAL_MAN
     *
     * @mbg.generated
     */
    private String dealMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.ACCEPT_OPINION
     *
     * @mbg.generated
     */
    private String acceptOpinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.IDCARD_TYPE
     *
     * @mbg.generated
     */
    private String idcardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.CONTACT_IDCARD_TYPE
     *
     * @mbg.generated
     */
    private String contactIdcardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.CONTACT_IDCARD
     *
     * @mbg.generated
     */
    private String contactIdcard;

    /**
     * Database Column Remarks:
     *   地区编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.area_code
     *
     * @mbg.generated
     */
    private String areaCode;

    /**
     * Database Column Remarks:
     *   实施机构组织机构代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.SS_ORGCODE
     *
     * @mbg.generated
     */
    private String ssOrgcode;

    /**
     * Database Column Remarks:
     *   受理部门
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.ACCEPT_DEPTID
     *
     * @mbg.generated
     */
    private String acceptDeptid;

    /**
     * Database Column Remarks:
     *   受理用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.ACCEPT_USERID
     *
     * @mbg.generated
     */
    private String acceptUserid;

    /**
     * Database Column Remarks:
     *   营业执照
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.BUSINESS_LICENSE
     *
     * @mbg.generated
     */
    private String businessLicense;

    /**
     * Database Column Remarks:
     *   事项所属部门id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.service_deptid
     *
     * @mbg.generated
     */
    private String serviceDeptid;

    /**
     * Database Column Remarks:
     *   申请人类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.APPLY_TYPE
     *
     * @mbg.generated
     */
    private String applyType;

    /**
     * Database Column Remarks:
     *   证照（或批文）状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.license_status
     *
     * @mbg.generated
     */
    private String licenseStatus;

    /**
     * Database Column Remarks:
     *   收件征询开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.receiveask_time
     *
     * @mbg.generated
     */
    private String receiveaskTime;

    /**
     * Database Column Remarks:
     *   收件征询部门
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.receiveask_deptid
     *
     * @mbg.generated
     */
    private String receiveaskDeptid;

    /**
     * Database Column Remarks:
     *   收件征询发起人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.receiveask_userid
     *
     * @mbg.generated
     */
    private String receiveaskUserid;

    /**
     * Database Column Remarks:
     *   收件征询结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.receiveask_end_time
     *
     * @mbg.generated
     */
    private String receiveaskEndTime;

    /**
     * Database Column Remarks:
     *   事项版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.SERVICE_VERSION
     *
     * @mbg.generated
     */
    private Integer serviceVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.certificate
     *
     * @mbg.generated
     */
    private String certificate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.create_deptid
     *
     * @mbg.generated
     */
    private String createDeptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.DATAVERSION
     *
     * @mbg.generated
     */
    private Integer dataversion;

    /**
     * Database Column Remarks:
     *   是否投资性项目
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.is_touzip
     *
     * @mbg.generated
     */
    private String isTouzip;

    /**
     * Database Column Remarks:
     *   该事项办件是否允许邮寄（Y：允许，N：不允许）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.needpost
     *
     * @mbg.generated
     */
    private String needpost;

    /**
     * Database Column Remarks:
     *   收件人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.contactman_post
     *
     * @mbg.generated
     */
    private String contactmanPost;

    /**
     * Database Column Remarks:
     *   收件人手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.mobile_post
     *
     * @mbg.generated
     */
    private String mobilePost;

    /**
     * Database Column Remarks:
     *   详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.address_post
     *
     * @mbg.generated
     */
    private String addressPost;

    /**
     * Database Column Remarks:
     *   是否收费
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.CHARGE_FLAG
     *
     * @mbg.generated
     */
    private String chargeFlag;

    /**
     * Database Column Remarks:
     *   收费金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.CHARGE_COST
     *
     * @mbg.generated
     */
    private String chargeCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.CHARGE_STATUS
     *
     * @mbg.generated
     */
    private String chargeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.areacode
     *
     * @mbg.generated
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.QL_REG_NO
     *
     * @mbg.generated
     */
    private String qlRegNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.DEPT_QL_REG_NO
     *
     * @mbg.generated
     */
    private String deptQlRegNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.DEPT_YW_REG_NO
     *
     * @mbg.generated
     */
    private String deptYwRegNo;

    /**
     * Database Column Remarks:
     *   市级政务服务系统的办件编号（各市政务服务系统内部唯一）,和各市政务服务中心编码（唯一）组成
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.INTERNAL_NO
     *
     * @mbg.generated
     */
    private String internalNo;

    /**
     * Database Column Remarks:
     *   默认I，同步成功S
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.ZWFWZX_CODE
     *
     * @mbg.generated
     */
    private String zwfwzxCode;

    /**
     * Database Column Remarks:
     *   同步至电子监察 默认I成功S
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.ess_sync
     *
     * @mbg.generated
     */
    private String essSync;

    /**
     * Database Column Remarks:
     *   受理人员电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.ysl_phone
     *
     * @mbg.generated
     */
    private String yslPhone;

    /**
     * Database Column Remarks:
     *   外网申报办件首页显示 默认I 成功S
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.backlog_sync
     *
     * @mbg.generated
     */
    private String backlogSync;

    /**
     * Database Column Remarks:
     *   默认I,在线办事为S
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.zxbs_sync
     *
     * @mbg.generated
     */
    private String zxbsSync;

    /**
     * Database Column Remarks:
     *   取事项库V4.0标准中实施主体编码（V3.1调整）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.ORG_ID
     *
     * @mbg.generated
     */
    private String orgId;

    /**
     * Database Column Remarks:
     *   评价渠道（pc端=1，移动端=2，二维码=3，政务大厅平板电脑=4，政务大厅其他终端=5，”12345”热线主动评价=6，短信=7，12345”热线回访评价=8,“我的连云港”app=9）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.pf
     *
     * @mbg.generated
     */
    private String pf;

    /**
     * Database Column Remarks:
     *   评价短信发送状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.pf_msg
     *
     * @mbg.generated
     */
    private String pfMsg;

    /**
     * Database Column Remarks:
     *   过程同步标识，默认I，成功S
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.logSync
     *
     * @mbg.generated
     */
    private String logsync;

    /**
     * Database Column Remarks:
     *   结果同步标识，默认I，成功S
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.overSync
     *
     * @mbg.generated
     */
    private String oversync;

    /**
     * Database Column Remarks:
     *   受理同步标识，默认I，成功
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.aSync
     *
     * @mbg.generated
     */
    private String async;

    /**
     * Database Column Remarks:
     *   办结同步标识，默认I，成功S
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.tSync
     *
     * @mbg.generated
     */
    private String tsync;

    /**
     * Database Column Remarks:
     *   后置办件unid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apas_info.next_unid
     *
     * @mbg.generated
     */
    private String nextUnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apas_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.UNID
     *
     * @return the value of apas_info.UNID
     *
     * @mbg.generated
     */
    public String getUnid() {
        return unid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.UNID
     *
     * @param unid the value for apas_info.UNID
     *
     * @mbg.generated
     */
    public void setUnid(String unid) {
        this.unid = unid;
    }

    public String getModuleUnid() {
        return moduleUnid;
    }

    public void setModuleUnid(String moduleUnid) {
        this.moduleUnid = moduleUnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.PARENTID
     *
     * @return the value of apas_info.PARENTID
     *
     * @mbg.generated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.PARENTID
     *
     * @param parentid the value for apas_info.PARENTID
     *
     * @mbg.generated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.SERVICEID
     *
     * @return the value of apas_info.SERVICEID
     *
     * @mbg.generated
     */
    public String getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.SERVICEID
     *
     * @param serviceid the value for apas_info.SERVICEID
     *
     * @mbg.generated
     */
    public void setServiceid(String serviceid) {
        this.serviceid = serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.SERVICENAME
     *
     * @return the value of apas_info.SERVICENAME
     *
     * @mbg.generated
     */
    public String getServicename() {
        return servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.SERVICENAME
     *
     * @param servicename the value for apas_info.SERVICENAME
     *
     * @mbg.generated
     */
    public void setServicename(String servicename) {
        this.servicename = servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.SERVICETYPE
     *
     * @return the value of apas_info.SERVICETYPE
     *
     * @mbg.generated
     */
    public String getServicetype() {
        return servicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.SERVICETYPE
     *
     * @param servicetype the value for apas_info.SERVICETYPE
     *
     * @mbg.generated
     */
    public void setServicetype(String servicetype) {
        this.servicetype = servicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.PROMISEDAY
     *
     * @return the value of apas_info.PROMISEDAY
     *
     * @mbg.generated
     */
    public Integer getPromiseday() {
        return promiseday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.PROMISEDAY
     *
     * @param promiseday the value for apas_info.PROMISEDAY
     *
     * @mbg.generated
     */
    public void setPromiseday(Integer promiseday) {
        this.promiseday = promiseday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.PROJ_CODE
     *
     * @return the value of apas_info.PROJ_CODE
     *
     * @mbg.generated
     */
    public String getProjCode() {
        return projCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.PROJ_CODE
     *
     * @param projCode the value for apas_info.PROJ_CODE
     *
     * @mbg.generated
     */
    public void setProjCode(String projCode) {
        this.projCode = projCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.INFOTYPE
     *
     * @return the value of apas_info.INFOTYPE
     *
     * @mbg.generated
     */
    public String getInfotype() {
        return infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.INFOTYPE
     *
     * @param infotype the value for apas_info.INFOTYPE
     *
     * @mbg.generated
     */
    public void setInfotype(String infotype) {
        this.infotype = infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.PROJID
     *
     * @return the value of apas_info.PROJID
     *
     * @mbg.generated
     */
    public String getProjid() {
        return projid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.PROJID
     *
     * @param projid the value for apas_info.PROJID
     *
     * @mbg.generated
     */
    public void setProjid(String projid) {
        this.projid = projid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.PROJPWD
     *
     * @return the value of apas_info.PROJPWD
     *
     * @mbg.generated
     */
    public String getProjpwd() {
        return projpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.PROJPWD
     *
     * @param projpwd the value for apas_info.PROJPWD
     *
     * @mbg.generated
     */
    public void setProjpwd(String projpwd) {
        this.projpwd = projpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.HANDLESTATE
     *
     * @return the value of apas_info.HANDLESTATE
     *
     * @mbg.generated
     */
    public String getHandlestate() {
        return handlestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.HANDLESTATE
     *
     * @param handlestate the value for apas_info.HANDLESTATE
     *
     * @mbg.generated
     */
    public void setHandlestate(String handlestate) {
        this.handlestate = handlestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.PROJECTNAME
     *
     * @return the value of apas_info.PROJECTNAME
     *
     * @mbg.generated
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.PROJECTNAME
     *
     * @param projectname the value for apas_info.PROJECTNAME
     *
     * @mbg.generated
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.APPLYNAME
     *
     * @return the value of apas_info.APPLYNAME
     *
     * @mbg.generated
     */
    public String getApplyname() {
        return applyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.APPLYNAME
     *
     * @param applyname the value for apas_info.APPLYNAME
     *
     * @mbg.generated
     */
    public void setApplyname(String applyname) {
        this.applyname = applyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.MOBILE
     *
     * @return the value of apas_info.MOBILE
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.MOBILE
     *
     * @param mobile the value for apas_info.MOBILE
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.PHONE
     *
     * @return the value of apas_info.PHONE
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.PHONE
     *
     * @param phone the value for apas_info.PHONE
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.ADDRESS
     *
     * @return the value of apas_info.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.ADDRESS
     *
     * @param address the value for apas_info.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.POSTCODE
     *
     * @return the value of apas_info.POSTCODE
     *
     * @mbg.generated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.POSTCODE
     *
     * @param postcode the value for apas_info.POSTCODE
     *
     * @mbg.generated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.EMAIL
     *
     * @return the value of apas_info.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.EMAIL
     *
     * @param email the value for apas_info.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.CONTACTMAN
     *
     * @return the value of apas_info.CONTACTMAN
     *
     * @mbg.generated
     */
    public String getContactman() {
        return contactman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.CONTACTMAN
     *
     * @param contactman the value for apas_info.CONTACTMAN
     *
     * @mbg.generated
     */
    public void setContactman(String contactman) {
        this.contactman = contactman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.LEGALMAN
     *
     * @return the value of apas_info.LEGALMAN
     *
     * @mbg.generated
     */
    public String getLegalman() {
        return legalman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.LEGALMAN
     *
     * @param legalman the value for apas_info.LEGALMAN
     *
     * @mbg.generated
     */
    public void setLegalman(String legalman) {
        this.legalman = legalman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.FORMID
     *
     * @return the value of apas_info.FORMID
     *
     * @mbg.generated
     */
    public String getFormid() {
        return formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.FORMID
     *
     * @param formid the value for apas_info.FORMID
     *
     * @mbg.generated
     */
    public void setFormid(String formid) {
        this.formid = formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.APPLYFROM
     *
     * @return the value of apas_info.APPLYFROM
     *
     * @mbg.generated
     */
    public String getApplyfrom() {
        return applyfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.APPLYFROM
     *
     * @param applyfrom the value for apas_info.APPLYFROM
     *
     * @mbg.generated
     */
    public void setApplyfrom(String applyfrom) {
        this.applyfrom = applyfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.IDCARD
     *
     * @return the value of apas_info.IDCARD
     *
     * @mbg.generated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.IDCARD
     *
     * @param idcard the value for apas_info.IDCARD
     *
     * @mbg.generated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.DELETEFLAG
     *
     * @return the value of apas_info.DELETEFLAG
     *
     * @mbg.generated
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.DELETEFLAG
     *
     * @param deleteflag the value for apas_info.DELETEFLAG
     *
     * @mbg.generated
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.CREATE_USERNAME
     *
     * @return the value of apas_info.CREATE_USERNAME
     *
     * @mbg.generated
     */
    public String getCreateUsername() {
        return createUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.CREATE_USERNAME
     *
     * @param createUsername the value for apas_info.CREATE_USERNAME
     *
     * @mbg.generated
     */
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.CREATE_USERID
     *
     * @return the value of apas_info.CREATE_USERID
     *
     * @mbg.generated
     */
    public String getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.CREATE_USERID
     *
     * @param createUserid the value for apas_info.CREATE_USERID
     *
     * @mbg.generated
     */
    public void setCreateUserid(String createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.CREATE_TIME
     *
     * @return the value of apas_info.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.CREATE_TIME
     *
     * @param createTime the value for apas_info.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.RECEIVE_USERNAME
     *
     * @return the value of apas_info.RECEIVE_USERNAME
     *
     * @mbg.generated
     */
    public String getReceiveUsername() {
        return receiveUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.RECEIVE_USERNAME
     *
     * @param receiveUsername the value for apas_info.RECEIVE_USERNAME
     *
     * @mbg.generated
     */
    public void setReceiveUsername(String receiveUsername) {
        this.receiveUsername = receiveUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.RECEIVE_USERID
     *
     * @return the value of apas_info.RECEIVE_USERID
     *
     * @mbg.generated
     */
    public String getReceiveUserid() {
        return receiveUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.RECEIVE_USERID
     *
     * @param receiveUserid the value for apas_info.RECEIVE_USERID
     *
     * @mbg.generated
     */
    public void setReceiveUserid(String receiveUserid) {
        this.receiveUserid = receiveUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.RECEIVE_DEPTNAME
     *
     * @return the value of apas_info.RECEIVE_DEPTNAME
     *
     * @mbg.generated
     */
    public String getReceiveDeptname() {
        return receiveDeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.RECEIVE_DEPTNAME
     *
     * @param receiveDeptname the value for apas_info.RECEIVE_DEPTNAME
     *
     * @mbg.generated
     */
    public void setReceiveDeptname(String receiveDeptname) {
        this.receiveDeptname = receiveDeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.RECEIVE_DEPTID
     *
     * @return the value of apas_info.RECEIVE_DEPTID
     *
     * @mbg.generated
     */
    public String getReceiveDeptid() {
        return receiveDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.RECEIVE_DEPTID
     *
     * @param receiveDeptid the value for apas_info.RECEIVE_DEPTID
     *
     * @mbg.generated
     */
    public void setReceiveDeptid(String receiveDeptid) {
        this.receiveDeptid = receiveDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.RECEIVE_TIME
     *
     * @return the value of apas_info.RECEIVE_TIME
     *
     * @mbg.generated
     */
    public String getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.RECEIVE_TIME
     *
     * @param receiveTime the value for apas_info.RECEIVE_TIME
     *
     * @mbg.generated
     */
    public void setReceiveTime(String receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.PREJUDGE_TIME
     *
     * @return the value of apas_info.PREJUDGE_TIME
     *
     * @mbg.generated
     */
    public String getPrejudgeTime() {
        return prejudgeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.PREJUDGE_TIME
     *
     * @param prejudgeTime the value for apas_info.PREJUDGE_TIME
     *
     * @mbg.generated
     */
    public void setPrejudgeTime(String prejudgeTime) {
        this.prejudgeTime = prejudgeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.ACCEPT_TIME
     *
     * @return the value of apas_info.ACCEPT_TIME
     *
     * @mbg.generated
     */
    public String getAcceptTime() {
        return acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.ACCEPT_TIME
     *
     * @param acceptTime the value for apas_info.ACCEPT_TIME
     *
     * @mbg.generated
     */
    public void setAcceptTime(String acceptTime) {
        this.acceptTime = acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.NODE_STIME
     *
     * @return the value of apas_info.NODE_STIME
     *
     * @mbg.generated
     */
    public String getNodeStime() {
        return nodeStime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.NODE_STIME
     *
     * @param nodeStime the value for apas_info.NODE_STIME
     *
     * @mbg.generated
     */
    public void setNodeStime(String nodeStime) {
        this.nodeStime = nodeStime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.NODE_ETIME
     *
     * @return the value of apas_info.NODE_ETIME
     *
     * @mbg.generated
     */
    public String getNodeEtime() {
        return nodeEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.NODE_ETIME
     *
     * @param nodeEtime the value for apas_info.NODE_ETIME
     *
     * @mbg.generated
     */
    public void setNodeEtime(String nodeEtime) {
        this.nodeEtime = nodeEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.TRANSACT_TIME
     *
     * @return the value of apas_info.TRANSACT_TIME
     *
     * @mbg.generated
     */
    public String getTransactTime() {
        return transactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.TRANSACT_TIME
     *
     * @param transactTime the value for apas_info.TRANSACT_TIME
     *
     * @mbg.generated
     */
    public void setTransactTime(String transactTime) {
        this.transactTime = transactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.GET_TIME
     *
     * @return the value of apas_info.GET_TIME
     *
     * @mbg.generated
     */
    public String getGetTime() {
        return getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.GET_TIME
     *
     * @param getTime the value for apas_info.GET_TIME
     *
     * @mbg.generated
     */
    public void setGetTime(String getTime) {
        this.getTime = getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.PROMISE_ETIME
     *
     * @return the value of apas_info.PROMISE_ETIME
     *
     * @mbg.generated
     */
    public String getPromiseEtime() {
        return promiseEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.PROMISE_ETIME
     *
     * @param promiseEtime the value for apas_info.PROMISE_ETIME
     *
     * @mbg.generated
     */
    public void setPromiseEtime(String promiseEtime) {
        this.promiseEtime = promiseEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.EFFISTATE
     *
     * @return the value of apas_info.EFFISTATE
     *
     * @mbg.generated
     */
    public String getEffistate() {
        return effistate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.EFFISTATE
     *
     * @param effistate the value for apas_info.EFFISTATE
     *
     * @mbg.generated
     */
    public void setEffistate(String effistate) {
        this.effistate = effistate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.EFFIVALUE
     *
     * @return the value of apas_info.EFFIVALUE
     *
     * @mbg.generated
     */
    public Integer getEffivalue() {
        return effivalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.EFFIVALUE
     *
     * @param effivalue the value for apas_info.EFFIVALUE
     *
     * @mbg.generated
     */
    public void setEffivalue(Integer effivalue) {
        this.effivalue = effivalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.MEMO
     *
     * @return the value of apas_info.MEMO
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.MEMO
     *
     * @param memo the value for apas_info.MEMO
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.GREEN_WAY
     *
     * @return the value of apas_info.GREEN_WAY
     *
     * @mbg.generated
     */
    public String getGreenWay() {
        return greenWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.GREEN_WAY
     *
     * @param greenWay the value for apas_info.GREEN_WAY
     *
     * @mbg.generated
     */
    public void setGreenWay(String greenWay) {
        this.greenWay = greenWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.APPLYCOUNT
     *
     * @return the value of apas_info.APPLYCOUNT
     *
     * @mbg.generated
     */
    public Integer getApplycount() {
        return applycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.APPLYCOUNT
     *
     * @param applycount the value for apas_info.APPLYCOUNT
     *
     * @mbg.generated
     */
    public void setApplycount(Integer applycount) {
        this.applycount = applycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.RESULT
     *
     * @return the value of apas_info.RESULT
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.RESULT
     *
     * @param result the value for apas_info.RESULT
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.RESULT_CODE
     *
     * @return the value of apas_info.RESULT_CODE
     *
     * @mbg.generated
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.RESULT_CODE
     *
     * @param resultCode the value for apas_info.RESULT_CODE
     *
     * @mbg.generated
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.UNITE_NOTICE_CODE
     *
     * @return the value of apas_info.UNITE_NOTICE_CODE
     *
     * @mbg.generated
     */
    public String getUniteNoticeCode() {
        return uniteNoticeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.UNITE_NOTICE_CODE
     *
     * @param uniteNoticeCode the value for apas_info.UNITE_NOTICE_CODE
     *
     * @mbg.generated
     */
    public void setUniteNoticeCode(String uniteNoticeCode) {
        this.uniteNoticeCode = uniteNoticeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.UNITE_PROJECT_INFO
     *
     * @return the value of apas_info.UNITE_PROJECT_INFO
     *
     * @mbg.generated
     */
    public String getUniteProjectInfo() {
        return uniteProjectInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.UNITE_PROJECT_INFO
     *
     * @param uniteProjectInfo the value for apas_info.UNITE_PROJECT_INFO
     *
     * @mbg.generated
     */
    public void setUniteProjectInfo(String uniteProjectInfo) {
        this.uniteProjectInfo = uniteProjectInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.UNITE_OPINION_CONTENT
     *
     * @return the value of apas_info.UNITE_OPINION_CONTENT
     *
     * @mbg.generated
     */
    public String getUniteOpinionContent() {
        return uniteOpinionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.UNITE_OPINION_CONTENT
     *
     * @param uniteOpinionContent the value for apas_info.UNITE_OPINION_CONTENT
     *
     * @mbg.generated
     */
    public void setUniteOpinionContent(String uniteOpinionContent) {
        this.uniteOpinionContent = uniteOpinionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.UNITE_OPINION_USERNAME
     *
     * @return the value of apas_info.UNITE_OPINION_USERNAME
     *
     * @mbg.generated
     */
    public String getUniteOpinionUsername() {
        return uniteOpinionUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.UNITE_OPINION_USERNAME
     *
     * @param uniteOpinionUsername the value for apas_info.UNITE_OPINION_USERNAME
     *
     * @mbg.generated
     */
    public void setUniteOpinionUsername(String uniteOpinionUsername) {
        this.uniteOpinionUsername = uniteOpinionUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.UNITE_OPINION_DATETIME
     *
     * @return the value of apas_info.UNITE_OPINION_DATETIME
     *
     * @mbg.generated
     */
    public String getUniteOpinionDatetime() {
        return uniteOpinionDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.UNITE_OPINION_DATETIME
     *
     * @param uniteOpinionDatetime the value for apas_info.UNITE_OPINION_DATETIME
     *
     * @mbg.generated
     */
    public void setUniteOpinionDatetime(String uniteOpinionDatetime) {
        this.uniteOpinionDatetime = uniteOpinionDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.UNITE_OPINION_USERUNID
     *
     * @return the value of apas_info.UNITE_OPINION_USERUNID
     *
     * @mbg.generated
     */
    public String getUniteOpinionUserunid() {
        return uniteOpinionUserunid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.UNITE_OPINION_USERUNID
     *
     * @param uniteOpinionUserunid the value for apas_info.UNITE_OPINION_USERUNID
     *
     * @mbg.generated
     */
    public void setUniteOpinionUserunid(String uniteOpinionUserunid) {
        this.uniteOpinionUserunid = uniteOpinionUserunid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.PROMISETYPE
     *
     * @return the value of apas_info.PROMISETYPE
     *
     * @mbg.generated
     */
    public String getPromisetype() {
        return promisetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.PROMISETYPE
     *
     * @param promisetype the value for apas_info.PROMISETYPE
     *
     * @mbg.generated
     */
    public void setPromisetype(String promisetype) {
        this.promisetype = promisetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.DISTANCEDAY
     *
     * @return the value of apas_info.DISTANCEDAY
     *
     * @mbg.generated
     */
    public Integer getDistanceday() {
        return distanceday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.DISTANCEDAY
     *
     * @param distanceday the value for apas_info.DISTANCEDAY
     *
     * @mbg.generated
     */
    public void setDistanceday(Integer distanceday) {
        this.distanceday = distanceday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.TERMINATE_USERID
     *
     * @return the value of apas_info.TERMINATE_USERID
     *
     * @mbg.generated
     */
    public String getTerminateUserid() {
        return terminateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.TERMINATE_USERID
     *
     * @param terminateUserid the value for apas_info.TERMINATE_USERID
     *
     * @mbg.generated
     */
    public void setTerminateUserid(String terminateUserid) {
        this.terminateUserid = terminateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.TERMINATE_USERNAME
     *
     * @return the value of apas_info.TERMINATE_USERNAME
     *
     * @mbg.generated
     */
    public String getTerminateUsername() {
        return terminateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.TERMINATE_USERNAME
     *
     * @param terminateUsername the value for apas_info.TERMINATE_USERNAME
     *
     * @mbg.generated
     */
    public void setTerminateUsername(String terminateUsername) {
        this.terminateUsername = terminateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.DEAL_OFFICE
     *
     * @return the value of apas_info.DEAL_OFFICE
     *
     * @mbg.generated
     */
    public String getDealOffice() {
        return dealOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.DEAL_OFFICE
     *
     * @param dealOffice the value for apas_info.DEAL_OFFICE
     *
     * @mbg.generated
     */
    public void setDealOffice(String dealOffice) {
        this.dealOffice = dealOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.DEAL_MAN
     *
     * @return the value of apas_info.DEAL_MAN
     *
     * @mbg.generated
     */
    public String getDealMan() {
        return dealMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.DEAL_MAN
     *
     * @param dealMan the value for apas_info.DEAL_MAN
     *
     * @mbg.generated
     */
    public void setDealMan(String dealMan) {
        this.dealMan = dealMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.ACCEPT_OPINION
     *
     * @return the value of apas_info.ACCEPT_OPINION
     *
     * @mbg.generated
     */
    public String getAcceptOpinion() {
        return acceptOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.ACCEPT_OPINION
     *
     * @param acceptOpinion the value for apas_info.ACCEPT_OPINION
     *
     * @mbg.generated
     */
    public void setAcceptOpinion(String acceptOpinion) {
        this.acceptOpinion = acceptOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.IDCARD_TYPE
     *
     * @return the value of apas_info.IDCARD_TYPE
     *
     * @mbg.generated
     */
    public String getIdcardType() {
        return idcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.IDCARD_TYPE
     *
     * @param idcardType the value for apas_info.IDCARD_TYPE
     *
     * @mbg.generated
     */
    public void setIdcardType(String idcardType) {
        this.idcardType = idcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.CONTACT_IDCARD_TYPE
     *
     * @return the value of apas_info.CONTACT_IDCARD_TYPE
     *
     * @mbg.generated
     */
    public String getContactIdcardType() {
        return contactIdcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.CONTACT_IDCARD_TYPE
     *
     * @param contactIdcardType the value for apas_info.CONTACT_IDCARD_TYPE
     *
     * @mbg.generated
     */
    public void setContactIdcardType(String contactIdcardType) {
        this.contactIdcardType = contactIdcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.CONTACT_IDCARD
     *
     * @return the value of apas_info.CONTACT_IDCARD
     *
     * @mbg.generated
     */
    public String getContactIdcard() {
        return contactIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.CONTACT_IDCARD
     *
     * @param contactIdcard the value for apas_info.CONTACT_IDCARD
     *
     * @mbg.generated
     */
    public void setContactIdcard(String contactIdcard) {
        this.contactIdcard = contactIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.area_code
     *
     * @return the value of apas_info.area_code
     *
     * @mbg.generated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.area_code
     *
     * @param areaCode the value for apas_info.area_code
     *
     * @mbg.generated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.SS_ORGCODE
     *
     * @return the value of apas_info.SS_ORGCODE
     *
     * @mbg.generated
     */
    public String getSsOrgcode() {
        return ssOrgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.SS_ORGCODE
     *
     * @param ssOrgcode the value for apas_info.SS_ORGCODE
     *
     * @mbg.generated
     */
    public void setSsOrgcode(String ssOrgcode) {
        this.ssOrgcode = ssOrgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.ACCEPT_DEPTID
     *
     * @return the value of apas_info.ACCEPT_DEPTID
     *
     * @mbg.generated
     */
    public String getAcceptDeptid() {
        return acceptDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.ACCEPT_DEPTID
     *
     * @param acceptDeptid the value for apas_info.ACCEPT_DEPTID
     *
     * @mbg.generated
     */
    public void setAcceptDeptid(String acceptDeptid) {
        this.acceptDeptid = acceptDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.ACCEPT_USERID
     *
     * @return the value of apas_info.ACCEPT_USERID
     *
     * @mbg.generated
     */
    public String getAcceptUserid() {
        return acceptUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.ACCEPT_USERID
     *
     * @param acceptUserid the value for apas_info.ACCEPT_USERID
     *
     * @mbg.generated
     */
    public void setAcceptUserid(String acceptUserid) {
        this.acceptUserid = acceptUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.BUSINESS_LICENSE
     *
     * @return the value of apas_info.BUSINESS_LICENSE
     *
     * @mbg.generated
     */
    public String getBusinessLicense() {
        return businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.BUSINESS_LICENSE
     *
     * @param businessLicense the value for apas_info.BUSINESS_LICENSE
     *
     * @mbg.generated
     */
    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.service_deptid
     *
     * @return the value of apas_info.service_deptid
     *
     * @mbg.generated
     */
    public String getServiceDeptid() {
        return serviceDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.service_deptid
     *
     * @param serviceDeptid the value for apas_info.service_deptid
     *
     * @mbg.generated
     */
    public void setServiceDeptid(String serviceDeptid) {
        this.serviceDeptid = serviceDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.APPLY_TYPE
     *
     * @return the value of apas_info.APPLY_TYPE
     *
     * @mbg.generated
     */
    public String getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.APPLY_TYPE
     *
     * @param applyType the value for apas_info.APPLY_TYPE
     *
     * @mbg.generated
     */
    public void setApplyType(String applyType) {
        this.applyType = applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.license_status
     *
     * @return the value of apas_info.license_status
     *
     * @mbg.generated
     */
    public String getLicenseStatus() {
        return licenseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.license_status
     *
     * @param licenseStatus the value for apas_info.license_status
     *
     * @mbg.generated
     */
    public void setLicenseStatus(String licenseStatus) {
        this.licenseStatus = licenseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.receiveask_time
     *
     * @return the value of apas_info.receiveask_time
     *
     * @mbg.generated
     */
    public String getReceiveaskTime() {
        return receiveaskTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.receiveask_time
     *
     * @param receiveaskTime the value for apas_info.receiveask_time
     *
     * @mbg.generated
     */
    public void setReceiveaskTime(String receiveaskTime) {
        this.receiveaskTime = receiveaskTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.receiveask_deptid
     *
     * @return the value of apas_info.receiveask_deptid
     *
     * @mbg.generated
     */
    public String getReceiveaskDeptid() {
        return receiveaskDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.receiveask_deptid
     *
     * @param receiveaskDeptid the value for apas_info.receiveask_deptid
     *
     * @mbg.generated
     */
    public void setReceiveaskDeptid(String receiveaskDeptid) {
        this.receiveaskDeptid = receiveaskDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.receiveask_userid
     *
     * @return the value of apas_info.receiveask_userid
     *
     * @mbg.generated
     */
    public String getReceiveaskUserid() {
        return receiveaskUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.receiveask_userid
     *
     * @param receiveaskUserid the value for apas_info.receiveask_userid
     *
     * @mbg.generated
     */
    public void setReceiveaskUserid(String receiveaskUserid) {
        this.receiveaskUserid = receiveaskUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.receiveask_end_time
     *
     * @return the value of apas_info.receiveask_end_time
     *
     * @mbg.generated
     */
    public String getReceiveaskEndTime() {
        return receiveaskEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.receiveask_end_time
     *
     * @param receiveaskEndTime the value for apas_info.receiveask_end_time
     *
     * @mbg.generated
     */
    public void setReceiveaskEndTime(String receiveaskEndTime) {
        this.receiveaskEndTime = receiveaskEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.SERVICE_VERSION
     *
     * @return the value of apas_info.SERVICE_VERSION
     *
     * @mbg.generated
     */
    public Integer getServiceVersion() {
        return serviceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.SERVICE_VERSION
     *
     * @param serviceVersion the value for apas_info.SERVICE_VERSION
     *
     * @mbg.generated
     */
    public void setServiceVersion(Integer serviceVersion) {
        this.serviceVersion = serviceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.certificate
     *
     * @return the value of apas_info.certificate
     *
     * @mbg.generated
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.certificate
     *
     * @param certificate the value for apas_info.certificate
     *
     * @mbg.generated
     */
    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.create_deptid
     *
     * @return the value of apas_info.create_deptid
     *
     * @mbg.generated
     */
    public String getCreateDeptid() {
        return createDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.create_deptid
     *
     * @param createDeptid the value for apas_info.create_deptid
     *
     * @mbg.generated
     */
    public void setCreateDeptid(String createDeptid) {
        this.createDeptid = createDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.DATAVERSION
     *
     * @return the value of apas_info.DATAVERSION
     *
     * @mbg.generated
     */
    public Integer getDataversion() {
        return dataversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.DATAVERSION
     *
     * @param dataversion the value for apas_info.DATAVERSION
     *
     * @mbg.generated
     */
    public void setDataversion(Integer dataversion) {
        this.dataversion = dataversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.is_touzip
     *
     * @return the value of apas_info.is_touzip
     *
     * @mbg.generated
     */
    public String getIsTouzip() {
        return isTouzip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.is_touzip
     *
     * @param isTouzip the value for apas_info.is_touzip
     *
     * @mbg.generated
     */
    public void setIsTouzip(String isTouzip) {
        this.isTouzip = isTouzip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.needpost
     *
     * @return the value of apas_info.needpost
     *
     * @mbg.generated
     */
    public String getNeedpost() {
        return needpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.needpost
     *
     * @param needpost the value for apas_info.needpost
     *
     * @mbg.generated
     */
    public void setNeedpost(String needpost) {
        this.needpost = needpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.contactman_post
     *
     * @return the value of apas_info.contactman_post
     *
     * @mbg.generated
     */
    public String getContactmanPost() {
        return contactmanPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.contactman_post
     *
     * @param contactmanPost the value for apas_info.contactman_post
     *
     * @mbg.generated
     */
    public void setContactmanPost(String contactmanPost) {
        this.contactmanPost = contactmanPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.mobile_post
     *
     * @return the value of apas_info.mobile_post
     *
     * @mbg.generated
     */
    public String getMobilePost() {
        return mobilePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.mobile_post
     *
     * @param mobilePost the value for apas_info.mobile_post
     *
     * @mbg.generated
     */
    public void setMobilePost(String mobilePost) {
        this.mobilePost = mobilePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.address_post
     *
     * @return the value of apas_info.address_post
     *
     * @mbg.generated
     */
    public String getAddressPost() {
        return addressPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.address_post
     *
     * @param addressPost the value for apas_info.address_post
     *
     * @mbg.generated
     */
    public void setAddressPost(String addressPost) {
        this.addressPost = addressPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.CHARGE_FLAG
     *
     * @return the value of apas_info.CHARGE_FLAG
     *
     * @mbg.generated
     */
    public String getChargeFlag() {
        return chargeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.CHARGE_FLAG
     *
     * @param chargeFlag the value for apas_info.CHARGE_FLAG
     *
     * @mbg.generated
     */
    public void setChargeFlag(String chargeFlag) {
        this.chargeFlag = chargeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.CHARGE_COST
     *
     * @return the value of apas_info.CHARGE_COST
     *
     * @mbg.generated
     */
    public String getChargeCost() {
        return chargeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.CHARGE_COST
     *
     * @param chargeCost the value for apas_info.CHARGE_COST
     *
     * @mbg.generated
     */
    public void setChargeCost(String chargeCost) {
        this.chargeCost = chargeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.CHARGE_STATUS
     *
     * @return the value of apas_info.CHARGE_STATUS
     *
     * @mbg.generated
     */
    public String getChargeStatus() {
        return chargeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.CHARGE_STATUS
     *
     * @param chargeStatus the value for apas_info.CHARGE_STATUS
     *
     * @mbg.generated
     */
    public void setChargeStatus(String chargeStatus) {
        this.chargeStatus = chargeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.areacode
     *
     * @return the value of apas_info.areacode
     *
     * @mbg.generated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.areacode
     *
     * @param areacode the value for apas_info.areacode
     *
     * @mbg.generated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.QL_REG_NO
     *
     * @return the value of apas_info.QL_REG_NO
     *
     * @mbg.generated
     */
    public String getQlRegNo() {
        return qlRegNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.QL_REG_NO
     *
     * @param qlRegNo the value for apas_info.QL_REG_NO
     *
     * @mbg.generated
     */
    public void setQlRegNo(String qlRegNo) {
        this.qlRegNo = qlRegNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.DEPT_QL_REG_NO
     *
     * @return the value of apas_info.DEPT_QL_REG_NO
     *
     * @mbg.generated
     */
    public String getDeptQlRegNo() {
        return deptQlRegNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.DEPT_QL_REG_NO
     *
     * @param deptQlRegNo the value for apas_info.DEPT_QL_REG_NO
     *
     * @mbg.generated
     */
    public void setDeptQlRegNo(String deptQlRegNo) {
        this.deptQlRegNo = deptQlRegNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.DEPT_YW_REG_NO
     *
     * @return the value of apas_info.DEPT_YW_REG_NO
     *
     * @mbg.generated
     */
    public String getDeptYwRegNo() {
        return deptYwRegNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.DEPT_YW_REG_NO
     *
     * @param deptYwRegNo the value for apas_info.DEPT_YW_REG_NO
     *
     * @mbg.generated
     */
    public void setDeptYwRegNo(String deptYwRegNo) {
        this.deptYwRegNo = deptYwRegNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.INTERNAL_NO
     *
     * @return the value of apas_info.INTERNAL_NO
     *
     * @mbg.generated
     */
    public String getInternalNo() {
        return internalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.INTERNAL_NO
     *
     * @param internalNo the value for apas_info.INTERNAL_NO
     *
     * @mbg.generated
     */
    public void setInternalNo(String internalNo) {
        this.internalNo = internalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.ZWFWZX_CODE
     *
     * @return the value of apas_info.ZWFWZX_CODE
     *
     * @mbg.generated
     */
    public String getZwfwzxCode() {
        return zwfwzxCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.ZWFWZX_CODE
     *
     * @param zwfwzxCode the value for apas_info.ZWFWZX_CODE
     *
     * @mbg.generated
     */
    public void setZwfwzxCode(String zwfwzxCode) {
        this.zwfwzxCode = zwfwzxCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.ess_sync
     *
     * @return the value of apas_info.ess_sync
     *
     * @mbg.generated
     */
    public String getEssSync() {
        return essSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.ess_sync
     *
     * @param essSync the value for apas_info.ess_sync
     *
     * @mbg.generated
     */
    public void setEssSync(String essSync) {
        this.essSync = essSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.ysl_phone
     *
     * @return the value of apas_info.ysl_phone
     *
     * @mbg.generated
     */
    public String getYslPhone() {
        return yslPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.ysl_phone
     *
     * @param yslPhone the value for apas_info.ysl_phone
     *
     * @mbg.generated
     */
    public void setYslPhone(String yslPhone) {
        this.yslPhone = yslPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.backlog_sync
     *
     * @return the value of apas_info.backlog_sync
     *
     * @mbg.generated
     */
    public String getBacklogSync() {
        return backlogSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.backlog_sync
     *
     * @param backlogSync the value for apas_info.backlog_sync
     *
     * @mbg.generated
     */
    public void setBacklogSync(String backlogSync) {
        this.backlogSync = backlogSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.zxbs_sync
     *
     * @return the value of apas_info.zxbs_sync
     *
     * @mbg.generated
     */
    public String getZxbsSync() {
        return zxbsSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.zxbs_sync
     *
     * @param zxbsSync the value for apas_info.zxbs_sync
     *
     * @mbg.generated
     */
    public void setZxbsSync(String zxbsSync) {
        this.zxbsSync = zxbsSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.ORG_ID
     *
     * @return the value of apas_info.ORG_ID
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.ORG_ID
     *
     * @param orgId the value for apas_info.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.pf
     *
     * @return the value of apas_info.pf
     *
     * @mbg.generated
     */
    public String getPf() {
        return pf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.pf
     *
     * @param pf the value for apas_info.pf
     *
     * @mbg.generated
     */
    public void setPf(String pf) {
        this.pf = pf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.pf_msg
     *
     * @return the value of apas_info.pf_msg
     *
     * @mbg.generated
     */
    public String getPfMsg() {
        return pfMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.pf_msg
     *
     * @param pfMsg the value for apas_info.pf_msg
     *
     * @mbg.generated
     */
    public void setPfMsg(String pfMsg) {
        this.pfMsg = pfMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.logSync
     *
     * @return the value of apas_info.logSync
     *
     * @mbg.generated
     */
    public String getLogsync() {
        return logsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.logSync
     *
     * @param logsync the value for apas_info.logSync
     *
     * @mbg.generated
     */
    public void setLogsync(String logsync) {
        this.logsync = logsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.overSync
     *
     * @return the value of apas_info.overSync
     *
     * @mbg.generated
     */
    public String getOversync() {
        return oversync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.overSync
     *
     * @param oversync the value for apas_info.overSync
     *
     * @mbg.generated
     */
    public void setOversync(String oversync) {
        this.oversync = oversync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.aSync
     *
     * @return the value of apas_info.aSync
     *
     * @mbg.generated
     */
    public String getAsync() {
        return async;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.aSync
     *
     * @param async the value for apas_info.aSync
     *
     * @mbg.generated
     */
    public void setAsync(String async) {
        this.async = async;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.tSync
     *
     * @return the value of apas_info.tSync
     *
     * @mbg.generated
     */
    public String getTsync() {
        return tsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.tSync
     *
     * @param tsync the value for apas_info.tSync
     *
     * @mbg.generated
     */
    public void setTsync(String tsync) {
        this.tsync = tsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apas_info.next_unid
     *
     * @return the value of apas_info.next_unid
     *
     * @mbg.generated
     */
    public String getNextUnid() {
        return nextUnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apas_info.next_unid
     *
     * @param nextUnid the value for apas_info.next_unid
     *
     * @mbg.generated
     */
    public void setNextUnid(String nextUnid) {
        this.nextUnid = nextUnid;
    }
}