package com.linewell.gg.dao.mapperwas.module;

import java.io.Serializable;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table module_instance
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ModuleInstance implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.unid
     *
     * @mbg.generated
     */
    private String unid;

    /**
     * Database Column Remarks:
     * 模板名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.module_name
     *
     * @mbg.generated
     */
    private String module_name;

    /**
     * Database Column Remarks:
     * 模板id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.module_unid
     *
     * @mbg.generated
     */
    private String module_unid;

    /**
     * Database Column Remarks:
     * 申请人
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.apply_name
     *
     * @mbg.generated
     */
    private String apply_name;

    /**
     * Database Column Remarks:
     * 申请人身份证
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.apply_idcard
     *
     * @mbg.generated
     */
    private String apply_idcard;

    /**
     * Database Column Remarks:
     * 申请人电话
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.apply_phone
     *
     * @mbg.generated
     */
    private String apply_phone;

    /**
     * Database Column Remarks:
     * 邮编
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.postcode
     *
     * @mbg.generated
     */
    private String postcode;

    /**
     * Database Column Remarks:
     * 联系人
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.contact_man
     *
     * @mbg.generated
     */
    private String contact_name;

    /**
     * Database Column Remarks:
     * 联系人电话
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.contact_phone
     *
     * @mbg.generated
     */
    private String contact_phone;

    /**
     * Database Column Remarks:
     * 项目名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.project_name
     *
     * @mbg.generated
     */
    private String project_name;

    /**
     * Database Column Remarks:
     * 创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.create_time
     *
     * @mbg.generated
     */
    private String create_time;

    /**
     * Database Column Remarks:
     * 申报类型
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.apply_type
     *
     * @mbg.generated
     */
    private String apply_type;

    /**
     * Database Column Remarks:
     * 法定代表人
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.legalman
     *
     * @mbg.generated
     */
    private String legalman;

    /**
     * Database Column Remarks:
     * 联系人身份证
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.contact_idcard
     *
     * @mbg.generated
     */
    private String contact_idcard;

    /**
     * Database Column Remarks:
     * 通讯地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     * 备注
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_instance.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table module_instance
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;


    private String serviceids;

    private String materialids;

    public String getServiceids() {
        return serviceids;
    }

    public void setServiceids(String serviceids) {
        this.serviceids = serviceids;
    }

    public String getMaterialids() {
        return materialids;
    }

    public void setMaterialids(String materialids) {
        this.materialids = materialids;
    }

    public String getUnid() {
        return unid;
    }

    public void setUnid(String unid) {
        this.unid = unid;
    }

    public String getModule_name() {
        return module_name;
    }

    public void setModule_name(String module_name) {
        this.module_name = module_name;
    }

    public String getModule_unid() {
        return module_unid;
    }

    public void setModule_unid(String module_unid) {
        this.module_unid = module_unid;
    }

    public String getApply_name() {
        return apply_name;
    }

    public void setApply_name(String apply_name) {
        this.apply_name = apply_name;
    }

    public String getApply_idcard() {
        return apply_idcard;
    }

    public void setApply_idcard(String apply_idcard) {
        this.apply_idcard = apply_idcard;
    }

    public String getApply_phone() {
        return apply_phone;
    }

    public void setApply_phone(String apply_phone) {
        this.apply_phone = apply_phone;
    }

    public String getPostcode() {
        return postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getContact_name() {
        return contact_name;
    }

    public void setContact_name(String contact_name) {
        this.contact_name = contact_name;
    }

    public String getContact_phone() {
        return contact_phone;
    }

    public void setContact_phone(String contact_phone) {
        this.contact_phone = contact_phone;
    }

    public String getProject_name() {
        return project_name;
    }

    public void setProject_name(String project_name) {
        this.project_name = project_name;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getApply_type() {
        return apply_type;
    }

    public void setApply_type(String apply_type) {
        this.apply_type = apply_type;
    }

    public String getLegalman() {
        return legalman;
    }

    public void setLegalman(String legalman) {
        this.legalman = legalman;
    }

    public String getContact_idcard() {
        return contact_idcard;
    }

    public void setContact_idcard(String contact_idcard) {
        this.contact_idcard = contact_idcard;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }
}